[package]
name = "kumo-server-lifecycle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
tracing = {workspace=true}
tokio = {workspace=true, features=["full", "tracing"]}
uuid = {workspace=true, features=["v4", "fast-rng"]}
