[package]
name = "traffic-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = {version="0.4", default-features=false, features=["clock"]}
clap = {version="4.1", features=["derive"]}
futures = "0.3"
humansize = "2.1" # for printing
humanize-rs = "0.1" # for parsing
lipsum = "0.9"
nix = {version="0.27", features=["resource"]}
num-format = "0.4"
once_cell = "1.17"
rand = "0.8"
rfc5321 = {path="../rfc5321"}
textwrap = "0.16"
tokio = {workspace=true, features=["full"]}
uuid = {workspace=true, features=["v4", "rng"]}
