[package]
name = "validate-shaping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = {version="4.5", features=["derive"]}
kumo-api-types = {path="../kumo-api-types", features=["lua"]}
tokio = {workspace=true, features=["full"]}
