[package]
name = "validate-shaping"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
clap = {workspace=true}
kumo-api-types = {path="../kumo-api-types", features=["lua"]}
tokio = {workspace=true, features=["full"]}
