# THIS FILE IS FOR COMMUNITY CONTRIBUTED BOUNCE CLASSIFICATION RULES
# THESE ARE PROVIDED AS-IS BY THEIR RESPECTIVE CONTRIBUTERS
# THIS FILE SHOULD BE USED IN COMBINATION WITH iana.toml TO GET FULL
# COVERAGE INCLUDING STATUS CODE BASED RULES.

# THIS FILE IS OVERWRITTEN DURING UPDATES, IF YOU MAKE CHANGES TO THIS FILE
# YOU WILL NEED TO DO A PULL REQUEST TO THE REPO AND HAVE IT ACCEPTED FOR 
# YOUR CHANGES TO PERSIST, OTHERWISE MAKE THESE CHANGES TO YOUR OWN CUSTOM
# BOUNCE RULES FILE:
# -- load the community bounces.toml + iana.toml + local settings
# kumo.on('init', function()
#   kumo.configure_local_logs {
#     log_dir = '/var/log/kumomta',
#   }
#   kumo.configure_bounce_classifier {
#     files = {
#       '/opt/kumomta/etc/policy/bounces.toml',
#       '/opt/kumomta/share/community/bounces.toml',
#        '/opt/kumomta/share/bounce_classifier/iana.toml',
#     },
#   }
# end)

[rules]
InvalidRecipient = [
  "Requested mail action aborted, mailbox not found", # Yahoo! Mail
  "mailbox unavailable", # Microsoft
  "User unknown in virtual mailbox table",
  "No such recipient here",
  "[nN]o [sS]uch [uU]ser",
  "No such mailbox",
  "Invalid Recipient", # Mimecast
  "I cannot deliver mail for",
  "Mailbox does not exist",
  "address unknown",
  "That recipient is not allowed",
  "Address invalid",
  "Address rejected",
  "User.+unknown$",
  "sorry, no mail-box here by that name",
  "No such ID",
  "Mailbox unavailable or access denied", # 58.com
  "User Unknown",
  "The mail server could not deliver mail to.+The account or domain may not exist, they may be blacklisted, or missing the proper dns entries",
  "address does not exist",
  "Message was not accepted -- invalid mailbox", # mail.ru
  "Utilisateur inconnu", # isep.fr (means unknown user)
  "sorry, no mailbox",
  "Not our Customer", # comcast.net
  "mailbox name not allowed", # citmo.net
  "recipient .+ denied",
  "Invalid account. Tenant or Domain not found",
  "Recipient address rejected: User unknown",
  "Recipient address rejected: unverified address",
  "recipient unrecognized",
  "permanent failure for one or more recipients",
  "Recipient address rejected: undeliverable address: No such user here",
  "User .+ does not exist",
  "^554.+undeliverable address",
  "^550.+not a valid user",
]
BadDomain = [
  "Recipient address has a null MX",
  "ResolvedAddress.+is on the list of prohibited_hosts",
  "The domain .+ is currently suspended",
]
InactiveMailbox = [
  "This mailbox is disabled", # Yahoo! Mail
  "The email account that you tried to reach is inactive", # Google
  "Account is not active",
  "User account not activated",
  "Account Closed, Please Remove", # comcast.net
  "this account is suspended",
  "Your message wasn't delivered due to an error; .+requires an upgrade to Enhanced Protection at .+forwardemail\\.net", # forwardemail.net
  "^550.+DisabledUser"
]
InvalidSender = [
]
QuotaIssues = [
  "inbox is out of storage space", # Google
  "Mailbox limit exeeded for this email address",
  "exceeded storage allocation Quota exceeded", #web.de
  "mailbox quota exceeded",
  "Mailbox is full",
  "Mailbox full",
  "Quota exceeded",
  "reached capacity or is overloaded",
  "^552.+extended quota violation",
  "^552.+OverQuotaPerm",
  "^550.+account is overquota",
]
NoAnswerFromHost = [
]
BadConnection = [
  "failed: invalid peer certificate: NotValidForName",
]
DNSFailure = [
  "MX didn't resolve to any hosts",
]
RoutingErrors = [
  "This mail server requires authentication when attempting to send to a non-local e-mail address",
  "relay not permitted",
  "isn't allowed to relay",
  "Unrouteable address",
  "^554.+MailLoop",
]
TransientFailure = [
  "Temporarily unable to process your email",
  "Error: transaction failed, blame it on the weather: E2: Cannot accept your message due to internal error, please report that to our engineers",
  "closing transmission channel - command timeout",
  "too many recent messages; Try again later",
  "Internal server error",
  "^550.+ReceivingRatePerm",
]
MessageExpired = [
]
ProtocolErrors = [
  "Bad sequence of commands",
  "failed to connect to any candidate hosts: All failures are related to OpportunisticInsecure STARTTLS.",
  "failed to connect to any candidate hosts: connect to ResolvedAddress.*read initial banner:",
  "failed to connect to any candidate hosts: TLS handshake with ResolvedAddress.*failed: tls handshake eof",
]
AuthenticationFailed = [
  "Authentication required",
  "Domain may not exist or DNS check failed",
  "Mail rejected. DMARC check failed.", #orange.fr
  "Access denied, sending domain.+does not pass DMARC verification and has a DMARC policy of reject",
  "Please turn on SMTP Authentication in your mail client",
  "Message rejected due to senders DMARC policy",
  "Sender Domain Resolve Fail",
  "sorry, your envelope sender domain must exist",
  "Domain of sender address .+ does not exist",
  "Sender .+ has no A, AAAA, or MX DNS records",
  "authentication required",
  "^550.+DmarcRejection",
]
PolicyRelated = [
  "DNSBL:RBL", # AT&T
  "greylisting as a means of reducing spam",
  "Greylisting in action",
  "Greylisting in place",
  "address rejected: Greylisted",
  "550 5\\.7\\.1", # Microsoft: Network is on our block list (S3150)
  "Email not accepted for policy reasons", # Yahoo
  "Reject due to policy restrictions", # web.de, GMX
  "Recipient address rejected: Access denied.", # outlook / microsoft
  "Invalid Sender. Your domain has been blacklisted", #orange.fr
  "Your access to this mail system has been rejected due to poor reputation of a domain used in message transfer",
  "REJECT spam",
  "Blocked Using Spam Pattern, Your Message May Contain The Spam Contents",
  "A URL in this email.+is listed on.+Please resolve and retry",
  "REJECTED - spamtext",
  "Your access to submit messages to this e-mail system has been rejected",
  "The sending IP.+is listed on.+Please resolve this and retry",
  "Blocked by ivmSIP",
  "Message rejected as spam",
  "Email blocked by cbl.abuseat.org",
  "Email rejected due to security policies",
  "sorry, that domain isn't in my list of allowed rcpthosts",
  "Your IP or Email address blocked by the FakeMail User",
  "spam message rejected", # mail.ru
  "Message denied", # duck.com
  "Recipient not on bypass list, your IP has been found on a block list",
  "JunkMail rejected",
  "Mail From Domain does not include a usable MX or A entry", # free.fr
  "Too many spams from your IP", # free.fr
  "We can't accept this message because it is spam", # wp.pl
  "Rejected - Content Policy",
  "Blocklisting in effect",
  "sender rejected AUP", # mms.att.net
  "blacklisted at zen.spamhaus.org",
  "Messages to .+ deferred due to excessive volume", # icloud
  "The recipient has exceeded their limit for the number of messages they can receive per hour.", # google
  "The user you are trying to contact is receiving mail at a rate that prevents additional messages from being delivered.", # google
  "^452.+restricted by policy error",
]
