[package]
name = "mod-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = {workspace=true}
config = {path="../config"}
data-encoding = {workspace=true}
mlua = {workspace=true, features=["serialize"]}
data-loader = {path="../data-loader", default-features=false}
ring = {workspace=true}
serde_json = {workspace=true}
aes-gcm = "0.10.3" 
rand = { version = "0.8", features = ["std"] } 
base64 = "0.22.1"
