[package]
name = "mod-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
aws-lc-rs.workspace = true
config = {path="../config"}
data-loader = {path="../data-loader"}
mlua = {workspace=true, features=["serialize"]}
mod-digest = {path="../mod-digest"}
serde.workspace = true

[dev-dependencies]
hex.workspace = true
