[package]
name = "mod-http"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
config = {path="../config"}
duration-serde = {path="../duration-serde"}
futures-util = {workspace=true}
humantime = {workspace=true}
mail-builder = {workspace=true}
mailparse = {workspace=true}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
reqwest = {workspace=true, default-features=false, features=["rustls-tls"]}
serde = {workspace=true}
tokio = {workspace=true}
tokio-tungstenite = {workspace=true}
