[package]
name = "kumo-spf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cidr = "0.2"
futures = {workspace=true}
hickory-resolver = {workspace=true}
thiserror = "1.0"

[dev-dependencies]
hickory-proto = {workspace=true, features = ["text-parsing"]}
k9 = "0.11"
tokio = {workspace = true, features = ["full", "tracing"]}
