[package]
name = "mod-string"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
config = {path="../config"}
kumo-template = {path="../kumo-template"}
kumo-wrap = {path="../kumo-wrap"}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
psl = {workspace=true}
