services:
  kumod:
    container_name: kumod
    hostname: kumod
    # use the latest build from `main`
    image: ghcr.io/kumocorp/kumomta:main
    # alternatively, use the latest stable release
    #image: ghcr.io/kumocorp/kumomta:latest
    volumes:
      - ./policy:/opt/kumomta/etc/policy
    restart: unless-stopped
    ports:
      - 25:2525
    depends_on:
      tsa:
        condition: service_healthy
  tsa:
    container_name: kumo-tsa
    hostname: tsa # The kumod policy scripts rely on this name
    image: ghcr.io/kumocorp/kumomta:main
    command: runuser -u kumod -- /opt/kumomta/sbin/tsa-daemon --policy /opt/kumomta/etc/policy/tsa_init.lua
    volumes:
      - ./policy:/opt/kumomta/etc/policy
    restart: unless-stopped
    healthcheck:
        test: /opt/kumomta/sbin/validate-shaping /opt/kumomta/etc/policy/shaping.toml || exit 1
        interval: 1s
        timeout: 2s
        retries: 3
