[package]
name = "mod-encode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
config = {path="../config"}
data-encoding = {workspace=true}
mlua = {workspace=true, features=["serialize"]}
