#!/bin/sh
CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-${PWD}/target}

for candidate in /opt/kumomta/sbin/kumod "${CARGO_TARGET_DIR}/release/kumod" "${CARGO_TARGET_DIR}/debug/kumod" ; do
  if test -x "${candidate}" ; then
    KUMOD="${candidate}"
    break;
  fi
done

if ! test -x "${KUMOD}" ; then
  echo "Couldn't find kumod"
  exit 1
fi

script=$(mktemp)
trap "rm -f -- '$script'" EXIT
cat >${script} <<-EOT
local kumo = require 'kumo'

kumo.on('main', function(domain)
  local mx = kumo.dns.lookup_mx(domain)
  print(mx.site_name)
end)
EOT

${KUMOD} --policy $script --script --script-args "$1"

