[package]
name = "mod-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
config = {path="../config"}
json_comments = {workspace=true}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
serde_json = {workspace=true}
serde_yaml = {workspace=true}
tokio = {workspace=true, features=["fs"]}
toml = {workspace=true}
