[package]
name = "tls-probe"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
clap = {workspace=true}
env_logger = {workspace=true}
kumo-api-types = {path="../kumo-api-types"}
log = {workspace=true}
rfc5321 = {path="../rfc5321"}
tokio = {workspace=true, features=["full"]}
tracing = {workspace=true, features=["log"]}
