(function() {var implementors = {
"bounce_classify":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"bounce_classify/enum.PreDefinedBounceClass.html\" title=\"enum bounce_classify::PreDefinedBounceClass\">PreDefinedBounceClass</a>"]],
"kumo_dkim":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"kumo_dkim/enum.DKIMError.html\" title=\"enum kumo_dkim::DKIMError\">DKIMError</a>"]],
"kumo_prometheus":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"kumo_prometheus/parser/struct.InternString.html\" title=\"struct kumo_prometheus::parser::InternString\">InternString</a>"]],
"kumo_server_common":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"kumo_server_common/nodeid/struct.NodeId.html\" title=\"struct kumo_server_common::nodeid::NodeId\">NodeId</a>"]],
"kumo_server_memory":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"kumo_server_memory/struct.MemoryLimits.html\" title=\"struct kumo_server_memory::MemoryLimits\">MemoryLimits</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"kumo_server_memory/struct.MemoryUsage.html\" title=\"struct kumo_server_memory::MemoryUsage\">MemoryUsage</a>"]],
"maildir":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"maildir/enum.MailEntryError.html\" title=\"enum maildir::MailEntryError\">MailEntryError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"maildir/enum.MaildirError.html\" title=\"enum maildir::MaildirError\">MaildirError</a>"]],
"mailparsing":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"mailparsing/enum.MailParsingError.html\" title=\"enum mailparsing::MailParsingError\">MailParsingError</a>"],["impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"mailparsing/enum.SharedString.html\" title=\"enum mailparsing::SharedString\">SharedString</a>&lt;'a&gt;"]],
"rfc5321":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"rfc5321/client/enum.ClientError.html\" title=\"enum rfc5321::client::ClientError\">ClientError</a>"]],
"spool":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"spool/spool_id/struct.SpoolId.html\" title=\"struct spool::spool_id::SpoolId\">SpoolId</a>"]],
"throttle":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"throttle/enum.Error.html\" title=\"enum throttle::Error\">Error</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.81.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"struct\" href=\"throttle/struct.ThrottleSpec.html\" title=\"struct throttle::ThrottleSpec\">ThrottleSpec</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()