labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0 # Need full history for doc build

when:
  - event: push
    branch:
      - main
    path: &paths
      include:
        - .woodpecker/docs.yml
        - assets/ci/populate-cache-vars.sh
        - docs/**
        - mkdocs-base.yml
        - stylua.toml
  - event: pull_request
    path: *paths
  - event: manual

steps:
  whoami:
    image: alpine:latest
    commands:
      - printenv CI_MACHINE

  pull-builder-image:
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    pull: true
    commands:
      - "true"

  setup-cache:
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    environment:
      GROUP: "docs"
    commands:
      - ./assets/ci/populate-cache-vars.sh

  build-docs:
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - . ./.cache-env
      - CI=true ./docs/build.sh

  run-mkdocs:
    image: ghcr.io/kumocorp/mkdocs-material:latest
    pull: true
    environment:
      CARDS: "true"
      GIT_DATES: "true"
    commands:
      - mkdocs build

  push-docs:
    when:
      - evaluate: '(CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "main") or (CI_PIPELINE_EVENT == "cron")'
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    environment:
      TOKEN:
        from_secret: gh_pages_deploy_token
    commands:
      - ./assets/ci/push-gh-pages.sh
