labels:
  platform: linux/amd64

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0 # Need full history for doc build

when:
  - event: push
    branch:
      - main
    path: &paths
      include:
        - .woodpecker/docs.yml
        - docs/**
        - mkdocs-base.yml
        - stylua.toml
  - event: pull_request
    path: *paths
  - event: manual

steps:
  restore-mtime:
    image: python:3-bookworm
    commands:
      - git config --global --add safe.directory /woodpecker/src
      - ./assets/ci/git-restore-mtime crates
      - git diff-index --name-status HEAD --

  setup-cache:
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    pull: true
    environment:
      GROUP: "docs"
    commands:
      - ./assets/ci/populate-cache-vars.sh

  build-docs:
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - . ./.cache-env
      - CI=true ./docs/build.sh

  run-mkdocs:
    image: woodpeckerci/plugin-mkdocs:latest
    pull: true
    environment:
      CARDS: "true"
      GIT_DATES: "true"
    settings:
      config: mkdocs.yml
      pip_install: "mkdocs-macros-plugin,mkdocs-include-markdown-plugin,mkdocs-exclude,mkdocs-git-revision-date-localized-plugin"

  push-docs:
    when:
      - evaluate: '(CI_PIPELINE_EVENT == "push" && CI_COMMIT_BRANCH == "main") or (CI_PIPELINE_EVENT == "cron")'
    image: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    environment:
      TOKEN:
        from_secret: gh_pages_deploy_token
    commands:
      - ./assets/ci/push-gh-pages.sh
