matrix:
  # Annoying workaround for <https://github.com/woodpecker-ci/woodpecker/issues/2002>
  include:
    - UBUNTU_VERSION: 22.04
      UBUNTU_IMAGE: ubuntu:22.04
      BUILDER_IMAGE: ghcr.io/kumocorp/builder-for-ubuntu:22.04
    #- UBUNTU_VERSION: 20.04
    #  UBUNTU_IMAGE: ubuntu:20.04
    #  BUILDER_IMAGE: ghcr.io/kumocorp/builder-for-ubuntu:20.04

when:
  - event: push
    branch:
      - main
  - event: pull_request
  - event: manual

variables:
  - &docker_credentials
      username:
        from_secret: gh_package_publish_user
      password:
        from_secret: gh_package_publish_token

steps:
  restore-mtime:
    image: python:3-bookworm
    commands:
      - git config --global --add safe.directory /woodpecker/src
      - ./assets/ci/git-restore-mtime crates
      - git diff-index --name-status HEAD --

  test:
    depends_on: [restore-mtime]
    environment: &cargo_environment
      CARGO_HOME: .ci-cargo
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: false
      AWS_ACCESS_KEY_ID:
        from_secret: s3_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: s3_secret_key
      SCCACHE_BUCKET: test-sccache
      SCCACHE_ENDPOINT:
        from_secret: s3_endpoint
      SCCACHE_REGION: auto
      SCCACHE_C_CUSTOM_CACHE_BUSTER: ubuntu:${UBUNTU_VERSION}_{{ arch }}_{{ os }}
    image: ${BUILDER_IMAGE}
    pull: true
    commands:
      - PATH=$PATH:$HOME/.cargo/bin
      - export RUSTC_WRAPPER=$HOME/.cargo/bin/sccache
      - ./get-deps.sh
      - git config --global --add safe.directory /woodpecker/src
      - make test

  build:
    depends_on: [test]
    environment: *cargo_environment
    image: ${BUILDER_IMAGE}
    pull: true
    commands:
      - PATH=$PATH:$HOME/.cargo/bin
      - make build BUILD_OPTS="--release"
      - ./assets/build-deb.sh

  verify-installable:
    depends_on: [build]
    image: ${UBUNTU_IMAGE}
    commands:
      - apt update
      - apt-get install -y ./kumomta*.deb

