name: Make Release

on:
  push:
    tags:
      - "20*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Changelog
        run: echo "See https://docs.kumomta.com/changelog/${{ github.ref_name }}" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Make Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          prerelease: true
          draft: true
