name: Publish Package Repos

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/publish-pkg-repos.yml"
      - "assets/yum.repos.d/*.repo"
      - "assets/sources.list.d/*.list"
      - "assets/upload-package.sh"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Publish"
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        TOKEN: ${{ secrets.OPENREPO_API_TOKEN }}
      shell: bash
      run: |
        ./assets/upload-package.sh files assets/yum.repos.d/*.repo assets/sources.list.d/*.list

